version: '3.1'
services:

  mongo:
    image: mongo
    ports: [ "27021:27017" ]
    networks: [ starter-net ]
    command: --logpath=/dev/null
    environment:
      TZ: America/Sao_Paulo

  starter:
    image: starter
    build: .
    command: ./start.sh
    env_file: [ ./.env ]
    volumes: [ ".:/usr/app/current" ]
    ports: [ "3002:3000" ]
    networks: [ starter-net ]
    links: [ mongo ]

networks:
    starter-net:
